name: Tests inside a Container
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    if: "!contains(github.event.head_commit.message, 'CI Bot')"

    steps:
      - uses: actions/checkout@v4

      - name: Show OS Info
        run: '[[ "$OSTYPE" == "linux-gnu"* ]] && { echo "OS Type: Linux"; (command -v lsb_release &> /dev/null && lsb_release -a) || cat /etc/os-release; uname -r; } || [[ "$OSTYPE" == "darwin"* ]] && { echo "OS Type: macOS"; sw_vers; uname -r; } || echo "Unsupported OS type: $OSTYPE"'

      - name: Build Flowcept's docker image
        run: make build

      - name: Start docker compose
        run: make services

      - name: Start docker compose
        run: make tests-in-docker
